##
## This file is automatically generated from template "/media/L3/home/bob/Stuff/cpp/qt-test-utils/src/autosubdirs/prjdir.pro.template".
## Any changes will be lost.
##

TEMPLATE = subdirs

include( ../../common.pri )
include( $$SOURCE_ROOT_DIR/autosubdirs/subdirs.pri )

addSubprojects( * )

