##
## This file is automatically generated from template "/media/L3/home/bob/Stuff/cpp/qt-test-utils/src/testutils-subdirtests/prjdir.pro.template".
## Any changes will be lost.
##

TEMPLATE = subdirs

include( /media/L3/home/bob/Stuff/cpp/qt-test-utils/src/common.pri )
include( /media/L3/home/bob/Stuff/cpp/qt-test-utils/src/testutils-subdirtests/subdirs.pri )

addSubprojects( $$PROJECT_NAME/*.pro )

